# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50939b8f6fd236e89aa1b4adfebb99024eb5fe8c6d4a7532d95a86d14c42167fb6a7e31915bd8e98698cc60975353d14f45510cd9c12389e92eab0364b8e6564

test:
  secret_key_base: 743fc05d8a2287afdec5983288c7bfaeac0615264d7e128fd9a85ff8aa72538030e0ac36c75c57c0d19a693b7ff2f7795d47907c9254978521bc5a56f2604158

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
